/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as PlacesRouteImport } from './routes/places'
import { Route as MyPostsRouteImport } from './routes/my-posts'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IncidentsRouteImport } from './routes/incidents'
import { Route as DirectionsRouteImport } from './routes/directions'
import { Route as CapturesRouteImport } from './routes/captures'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RoutesIndexRouteImport } from './routes/routes/index'
import { Route as SettingsOfflineRouteImport } from './routes/settings/offline'
import { Route as SequenceAuthorIdSequenceIdRouteImport } from './routes/sequence/$authorId.$sequenceId'
import { Route as RouteAuthorIdRouteIdRouteImport } from './routes/route/$authorId.$routeId'
import { Route as PlaceOsmTypeOsmIdRouteImport } from './routes/place/$osmType.$osmId'
import { Route as IncidentAuthorIdIncidentIdRouteImport } from './routes/incident/$authorId.$incidentId'
import { Route as CaptureAuthorIdCaptureIdRouteImport } from './routes/capture/$authorId.$captureId'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const PlacesRoute = PlacesRouteImport.update({
  id: '/places',
  path: '/places',
  getParentRoute: () => rootRouteImport,
} as any)
const MyPostsRoute = MyPostsRouteImport.update({
  id: '/my-posts',
  path: '/my-posts',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IncidentsRoute = IncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectionsRoute = DirectionsRouteImport.update({
  id: '/directions',
  path: '/directions',
  getParentRoute: () => rootRouteImport,
} as any)
const CapturesRoute = CapturesRouteImport.update({
  id: '/captures',
  path: '/captures',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutesIndexRoute = RoutesIndexRouteImport.update({
  id: '/routes/',
  path: '/routes/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsOfflineRoute = SettingsOfflineRouteImport.update({
  id: '/settings/offline',
  path: '/settings/offline',
  getParentRoute: () => rootRouteImport,
} as any)
const SequenceAuthorIdSequenceIdRoute =
  SequenceAuthorIdSequenceIdRouteImport.update({
    id: '/sequence/$authorId/$sequenceId',
    path: '/sequence/$authorId/$sequenceId',
    getParentRoute: () => rootRouteImport,
  } as any)
const RouteAuthorIdRouteIdRoute = RouteAuthorIdRouteIdRouteImport.update({
  id: '/route/$authorId/$routeId',
  path: '/route/$authorId/$routeId',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaceOsmTypeOsmIdRoute = PlaceOsmTypeOsmIdRouteImport.update({
  id: '/place/$osmType/$osmId',
  path: '/place/$osmType/$osmId',
  getParentRoute: () => rootRouteImport,
} as any)
const IncidentAuthorIdIncidentIdRoute =
  IncidentAuthorIdIncidentIdRouteImport.update({
    id: '/incident/$authorId/$incidentId',
    path: '/incident/$authorId/$incidentId',
    getParentRoute: () => rootRouteImport,
  } as any)
const CaptureAuthorIdCaptureIdRoute =
  CaptureAuthorIdCaptureIdRouteImport.update({
    id: '/capture/$authorId/$captureId',
    path: '/capture/$authorId/$captureId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/captures': typeof CapturesRoute
  '/directions': typeof DirectionsRoute
  '/incidents': typeof IncidentsRoute
  '/login': typeof LoginRoute
  '/my-posts': typeof MyPostsRoute
  '/places': typeof PlacesRoute
  '/search': typeof SearchRoute
  '/settings/offline': typeof SettingsOfflineRoute
  '/routes/': typeof RoutesIndexRoute
  '/capture/$authorId/$captureId': typeof CaptureAuthorIdCaptureIdRoute
  '/incident/$authorId/$incidentId': typeof IncidentAuthorIdIncidentIdRoute
  '/place/$osmType/$osmId': typeof PlaceOsmTypeOsmIdRoute
  '/route/$authorId/$routeId': typeof RouteAuthorIdRouteIdRoute
  '/sequence/$authorId/$sequenceId': typeof SequenceAuthorIdSequenceIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/captures': typeof CapturesRoute
  '/directions': typeof DirectionsRoute
  '/incidents': typeof IncidentsRoute
  '/login': typeof LoginRoute
  '/my-posts': typeof MyPostsRoute
  '/places': typeof PlacesRoute
  '/search': typeof SearchRoute
  '/settings/offline': typeof SettingsOfflineRoute
  '/routes': typeof RoutesIndexRoute
  '/capture/$authorId/$captureId': typeof CaptureAuthorIdCaptureIdRoute
  '/incident/$authorId/$incidentId': typeof IncidentAuthorIdIncidentIdRoute
  '/place/$osmType/$osmId': typeof PlaceOsmTypeOsmIdRoute
  '/route/$authorId/$routeId': typeof RouteAuthorIdRouteIdRoute
  '/sequence/$authorId/$sequenceId': typeof SequenceAuthorIdSequenceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/captures': typeof CapturesRoute
  '/directions': typeof DirectionsRoute
  '/incidents': typeof IncidentsRoute
  '/login': typeof LoginRoute
  '/my-posts': typeof MyPostsRoute
  '/places': typeof PlacesRoute
  '/search': typeof SearchRoute
  '/settings/offline': typeof SettingsOfflineRoute
  '/routes/': typeof RoutesIndexRoute
  '/capture/$authorId/$captureId': typeof CaptureAuthorIdCaptureIdRoute
  '/incident/$authorId/$incidentId': typeof IncidentAuthorIdIncidentIdRoute
  '/place/$osmType/$osmId': typeof PlaceOsmTypeOsmIdRoute
  '/route/$authorId/$routeId': typeof RouteAuthorIdRouteIdRoute
  '/sequence/$authorId/$sequenceId': typeof SequenceAuthorIdSequenceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/captures'
    | '/directions'
    | '/incidents'
    | '/login'
    | '/my-posts'
    | '/places'
    | '/search'
    | '/settings/offline'
    | '/routes/'
    | '/capture/$authorId/$captureId'
    | '/incident/$authorId/$incidentId'
    | '/place/$osmType/$osmId'
    | '/route/$authorId/$routeId'
    | '/sequence/$authorId/$sequenceId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/captures'
    | '/directions'
    | '/incidents'
    | '/login'
    | '/my-posts'
    | '/places'
    | '/search'
    | '/settings/offline'
    | '/routes'
    | '/capture/$authorId/$captureId'
    | '/incident/$authorId/$incidentId'
    | '/place/$osmType/$osmId'
    | '/route/$authorId/$routeId'
    | '/sequence/$authorId/$sequenceId'
  id:
    | '__root__'
    | '/'
    | '/captures'
    | '/directions'
    | '/incidents'
    | '/login'
    | '/my-posts'
    | '/places'
    | '/search'
    | '/settings/offline'
    | '/routes/'
    | '/capture/$authorId/$captureId'
    | '/incident/$authorId/$incidentId'
    | '/place/$osmType/$osmId'
    | '/route/$authorId/$routeId'
    | '/sequence/$authorId/$sequenceId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CapturesRoute: typeof CapturesRoute
  DirectionsRoute: typeof DirectionsRoute
  IncidentsRoute: typeof IncidentsRoute
  LoginRoute: typeof LoginRoute
  MyPostsRoute: typeof MyPostsRoute
  PlacesRoute: typeof PlacesRoute
  SearchRoute: typeof SearchRoute
  SettingsOfflineRoute: typeof SettingsOfflineRoute
  RoutesIndexRoute: typeof RoutesIndexRoute
  CaptureAuthorIdCaptureIdRoute: typeof CaptureAuthorIdCaptureIdRoute
  IncidentAuthorIdIncidentIdRoute: typeof IncidentAuthorIdIncidentIdRoute
  PlaceOsmTypeOsmIdRoute: typeof PlaceOsmTypeOsmIdRoute
  RouteAuthorIdRouteIdRoute: typeof RouteAuthorIdRouteIdRoute
  SequenceAuthorIdSequenceIdRoute: typeof SequenceAuthorIdSequenceIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/places': {
      id: '/places'
      path: '/places'
      fullPath: '/places'
      preLoaderRoute: typeof PlacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-posts': {
      id: '/my-posts'
      path: '/my-posts'
      fullPath: '/my-posts'
      preLoaderRoute: typeof MyPostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incidents': {
      id: '/incidents'
      path: '/incidents'
      fullPath: '/incidents'
      preLoaderRoute: typeof IncidentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directions': {
      id: '/directions'
      path: '/directions'
      fullPath: '/directions'
      preLoaderRoute: typeof DirectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/captures': {
      id: '/captures'
      path: '/captures'
      fullPath: '/captures'
      preLoaderRoute: typeof CapturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routes/': {
      id: '/routes/'
      path: '/routes'
      fullPath: '/routes/'
      preLoaderRoute: typeof RoutesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/offline': {
      id: '/settings/offline'
      path: '/settings/offline'
      fullPath: '/settings/offline'
      preLoaderRoute: typeof SettingsOfflineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sequence/$authorId/$sequenceId': {
      id: '/sequence/$authorId/$sequenceId'
      path: '/sequence/$authorId/$sequenceId'
      fullPath: '/sequence/$authorId/$sequenceId'
      preLoaderRoute: typeof SequenceAuthorIdSequenceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/route/$authorId/$routeId': {
      id: '/route/$authorId/$routeId'
      path: '/route/$authorId/$routeId'
      fullPath: '/route/$authorId/$routeId'
      preLoaderRoute: typeof RouteAuthorIdRouteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/place/$osmType/$osmId': {
      id: '/place/$osmType/$osmId'
      path: '/place/$osmType/$osmId'
      fullPath: '/place/$osmType/$osmId'
      preLoaderRoute: typeof PlaceOsmTypeOsmIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incident/$authorId/$incidentId': {
      id: '/incident/$authorId/$incidentId'
      path: '/incident/$authorId/$incidentId'
      fullPath: '/incident/$authorId/$incidentId'
      preLoaderRoute: typeof IncidentAuthorIdIncidentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capture/$authorId/$captureId': {
      id: '/capture/$authorId/$captureId'
      path: '/capture/$authorId/$captureId'
      fullPath: '/capture/$authorId/$captureId'
      preLoaderRoute: typeof CaptureAuthorIdCaptureIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CapturesRoute: CapturesRoute,
  DirectionsRoute: DirectionsRoute,
  IncidentsRoute: IncidentsRoute,
  LoginRoute: LoginRoute,
  MyPostsRoute: MyPostsRoute,
  PlacesRoute: PlacesRoute,
  SearchRoute: SearchRoute,
  SettingsOfflineRoute: SettingsOfflineRoute,
  RoutesIndexRoute: RoutesIndexRoute,
  CaptureAuthorIdCaptureIdRoute: CaptureAuthorIdCaptureIdRoute,
  IncidentAuthorIdIncidentIdRoute: IncidentAuthorIdIncidentIdRoute,
  PlaceOsmTypeOsmIdRoute: PlaceOsmTypeOsmIdRoute,
  RouteAuthorIdRouteIdRoute: RouteAuthorIdRouteIdRoute,
  SequenceAuthorIdSequenceIdRoute: SequenceAuthorIdSequenceIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
